// Code generated by MockGen. DO NOT EDIT.
// Source: internal/enrich/http.go
//
// Generated by this command:
//
//	mockgen -source internal/enrich/http.go -destination mock/enrich/http.go
//

// Package mock_enrich is a generated GoMock package.
package mock_enrich

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// FetchIssue mocks base method.
func (m *MockHTTPClient) FetchIssue(token, repo, number string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchIssue", token, repo, number)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchIssue indicates an expected call of FetchIssue.
func (mr *MockHTTPClientMockRecorder) FetchIssue(token, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchIssue", reflect.TypeOf((*MockHTTPClient)(nil).FetchIssue), token, repo, number)
}

// FetchPullRequest mocks base method.
func (m *MockHTTPClient) FetchPullRequest(token, repo, number string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPullRequest", token, repo, number)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPullRequest indicates an expected call of FetchPullRequest.
func (mr *MockHTTPClientMockRecorder) FetchPullRequest(token, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPullRequest", reflect.TypeOf((*MockHTTPClient)(nil).FetchPullRequest), token, repo, number)
}

// FetchRepository mocks base method.
func (m *MockHTTPClient) FetchRepository(token, repo string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRepository", token, repo)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRepository indicates an expected call of FetchRepository.
func (mr *MockHTTPClientMockRecorder) FetchRepository(token, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRepository", reflect.TypeOf((*MockHTTPClient)(nil).FetchRepository), token, repo)
}
