// Code generated by MockGen. DO NOT EDIT.
// Source: internal/enrich/http.go
//
// Generated by this command:
//
//	mockgen -source internal/enrich/http.go -destination mock/enrich/http.go
//

// Package mock_enrich is a generated GoMock package.
package mock_enrich

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// FetchChannel mocks base method.
func (m *MockHTTPClient) FetchChannel(token, channelID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchChannel", token, channelID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchChannel indicates an expected call of FetchChannel.
func (mr *MockHTTPClientMockRecorder) FetchChannel(token, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchChannel", reflect.TypeOf((*MockHTTPClient)(nil).FetchChannel), token, channelID)
}

// FetchThread mocks base method.
func (m *MockHTTPClient) FetchThread(token, channelID, threadTS string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchThread", token, channelID, threadTS)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchThread indicates an expected call of FetchThread.
func (mr *MockHTTPClientMockRecorder) FetchThread(token, channelID, threadTS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchThread", reflect.TypeOf((*MockHTTPClient)(nil).FetchThread), token, channelID, threadTS)
}
