// THIS FILE WAS GENERATED BY `xtp-go-bindgen`. DO NOT EDIT.
package main

import (
	
	"time"

	pdk "github.com/extism/go-pdk"
)

//export EnrichContext
func _EnrichContext() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "EnrichContext: getting JSON input")
			var input EnrichRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "EnrichContext: calling implementation function")
          output, err := EnrichContext(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
      			pdk.Log(pdk.LogDebug, "EnrichContext: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "EnrichContext: returning")
  return 0
}

//export FetchActivities
func _FetchActivities() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "FetchActivities: getting JSON input")
			var input FetchRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "FetchActivities: calling implementation function")
          output, err := FetchActivities(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
      			pdk.Log(pdk.LogDebug, "FetchActivities: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "FetchActivities: returning")
  return 0
}

//export GetConfigSchema
func _GetConfigSchema() int32 {
	var err error
	_ = err
            output, err := GetConfigSchema()
    		if err != nil {
			pdk.SetError(err)
			return -1
		}
  
      			pdk.Log(pdk.LogDebug, "GetConfigSchema: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "GetConfigSchema: returning")
  return 0
}

//export GetContextPatterns
func _GetContextPatterns() int32 {
	var err error
	_ = err
            output, err := GetContextPatterns()
    		if err != nil {
			pdk.SetError(err)
			return -1
		}
  
      			pdk.Log(pdk.LogDebug, "GetContextPatterns: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "GetContextPatterns: returning")
  return 0
}

//export TestConnection
func _TestConnection() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "TestConnection: getting JSON input")
			var input TestConnectionRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "TestConnection: calling implementation function")
          err = TestConnection(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
  
	pdk.Log(pdk.LogDebug, "TestConnection: returning")
  return 0
}




	
	
		
	
	// 
	type Activity struct {
						ActivityType string `json:"activityType"`
						Contexts []Context `json:"contexts"`
						Description *string `json:"description,omitempty"`
						Id string `json:"id"`
						Metadata interface{} `json:"metadata"`
						Source string `json:"source"`
						Timestamp time.Time `json:"timestamp"`
						Title string `json:"title"`
						Url *string `json:"url,omitempty"`
		
	}
		
	
		
	
	// 
	type ConfigSchema struct {
						Properties interface{} `json:"properties"`
						Required *[]string `json:"required,omitempty"`
						Type string `json:"type"`
		
	}
		
	
		
	
	// 
	type Context struct {
						ConnectorId string `json:"connectorId"`
						CreatedAt *time.Time `json:"createdAt,omitempty"`
						Description *string `json:"description,omitempty"`
						Id string `json:"id"`
						Level int64 `json:"level"`
						Metadata interface{} `json:"metadata"`
						Name string `json:"name"`
						ParentId string `json:"parentId"`
						// Resource type (e.g., 'source', 'repository', 'pull_request', 'issue', 'channel', 'thread')
				ResourceType string `json:"resourceType"`
						Title *string `json:"title,omitempty"`
						UpdatedAt *time.Time `json:"updatedAt,omitempty"`
						Url *string `json:"url,omitempty"`
		
	}
		
	
		
	
	// 
	type ContextMapping struct {
						// Parameters for enrichment using {{groupName}} templates (e.g., {'repo': '{{owner}}/{{repo}}', 'pr_number': '{{number}}'})
				EnrichmentParams interface{} `json:"enrichmentParams,omitempty"`
						// Template for context ID using {{groupName}} placeholders (e.g., 'repository:{{owner}}/{{repo}}')
				IdTemplate string `json:"idTemplate"`
						// Hierarchy level (1=source, 2=repository, 3=PR/Issue)
				Level int64 `json:"level"`
						// Template for context name using {{groupName}} placeholders (e.g., 'repository:{{owner}}/{{repo}}'). For static names, use plain strings without placeholders (e.g., 'github:source').
				NameTemplate string `json:"nameTemplate"`
						// Index of parent context in contextMappings array (null for root/level 1)
				ParentIndex *int64 `json:"parentIndex,omitempty"`
						// Resource type identifier (e.g., 'source', 'repository', 'pull_request', 'issue', 'channel', 'thread')
				ResourceType string `json:"resourceType"`
		
	}
		
	
		
	
	// 
	type ContextPatternDefinition struct {
						// List of context mappings to create from URL pattern matches
				ContextMappings []ContextMapping `json:"contextMappings"`
						// Regex pattern with named groups (e.g., 'https://github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)/pull/(?P<number>\d+)')
				Pattern string `json:"pattern"`
		
	}
		
	
		
	
	// 
	type ContextPatternsResponse struct {
						Patterns []ContextPatternDefinition `json:"patterns"`
		
	}
		
	
		
	
	// 
	type EnrichRequest struct {
						Config interface{} `json:"config"`
						Context Context `json:"context"`
		
	}
		
	
		
	
	// 
	type EnrichResponse struct {
						Context Context `json:"context"`
		
	}
		
	
		
	
	// 
	type FetchParams struct {
						TargetDate string `json:"targetDate"`
		
	}
		
	
		
	
	// 
	type FetchRequest struct {
						Config interface{} `json:"config"`
						Params FetchParams `json:"params"`
		
	}
		
	
		
	
	// 
	type FetchResponse struct {
						Activities []Activity `json:"activities"`
		
	}
		
	
		
	
	// 
	type TestConnectionRequest struct {
						// Connector configuration including credentials
				Config interface{} `json:"config"`
		
	}
		
	


