// Code generated by MockGen. DO NOT EDIT.
// Source: internal/fetch/http.go
//
// Generated by this command:
//
//	mockgen -source internal/fetch/http.go -destination mock/fetch/http.go
//

// Package mock_fetch is a generated GoMock package.
package mock_fetch

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// FetchActivities mocks base method.
func (m *MockHTTPClient) FetchActivities(token, username string, page int) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchActivities", token, username, page)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchActivities indicates an expected call of FetchActivities.
func (mr *MockHTTPClientMockRecorder) FetchActivities(token, username, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchActivities", reflect.TypeOf((*MockHTTPClient)(nil).FetchActivities), token, username, page)
}
