// THIS FILE WAS GENERATED BY `xtp-go-bindgen`. DO NOT EDIT.
package main

import (
	
	"time"

	pdk "github.com/extism/go-pdk"
)

//export EnrichContext
func _EnrichContext() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "EnrichContext: getting JSON input")
			var input EnrichRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "EnrichContext: calling implementation function")
          output, err := EnrichContext(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
      			pdk.Log(pdk.LogDebug, "EnrichContext: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "EnrichContext: returning")
  return 0
}

//export FetchActivities
func _FetchActivities() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "FetchActivities: getting JSON input")
			var input FetchRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "FetchActivities: calling implementation function")
          output, err := FetchActivities(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
      			pdk.Log(pdk.LogDebug, "FetchActivities: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "FetchActivities: returning")
  return 0
}

//export GetConfigSchema
func _GetConfigSchema() int32 {
	var err error
	_ = err
            output, err := GetConfigSchema()
    		if err != nil {
			pdk.SetError(err)
			return -1
		}
  
      			pdk.Log(pdk.LogDebug, "GetConfigSchema: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "GetConfigSchema: returning")
  return 0
}

//export MatchContext
func _MatchContext() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "MatchContext: getting JSON input")
			var input MatchContextRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "MatchContext: calling implementation function")
          output, err := MatchContext(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
      			pdk.Log(pdk.LogDebug, "MatchContext: setting JSON output")
			err = pdk.OutputJSON(output)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
	pdk.Log(pdk.LogDebug, "MatchContext: returning")
  return 0
}

//export TestConnection
func _TestConnection() int32 {
	var err error
	_ = err
      			pdk.Log(pdk.LogDebug, "TestConnection: getting JSON input")
			var input TestConnectionRequest
			err = pdk.InputJSON(&input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
    
		pdk.Log(pdk.LogDebug, "TestConnection: calling implementation function")
          err = TestConnection(input)
			if err != nil {
				pdk.SetError(err)
				return -1
			}
      
  
	pdk.Log(pdk.LogDebug, "TestConnection: returning")
  return 0
}




	
	
		
	
	// 
	type Activity struct {
						ActivityType string `json:"activityType"`
						Contexts []Context `json:"contexts"`
						Description string `json:"description"`
						Id string `json:"id"`
						Metadata interface{} `json:"metadata"`
						Source string `json:"source"`
						Timestamp time.Time `json:"timestamp"`
						Title string `json:"title"`
						Url *string `json:"url,omitempty"`
		
	}
		
	
		
	
	// 
	type ConfigSchema struct {
						Properties interface{} `json:"properties"`
						Required *[]string `json:"required,omitempty"`
						Type string `json:"type"`
		
	}
		
	
		
	
	// 
	type Context struct {
						ConnectorId string `json:"connectorId"`
						CreatedAt *time.Time `json:"createdAt,omitempty"`
						Description *string `json:"description,omitempty"`
						Id string `json:"id"`
						Metadata interface{} `json:"metadata"`
						Name string `json:"name"`
						ParentId string `json:"parentId"`
						// Resource type (e.g., 'source', 'repository', 'pull_request', 'issue', 'channel', 'thread')
				ResourceType string `json:"resourceType"`
						Title *string `json:"title,omitempty"`
						UpdatedAt *time.Time `json:"updatedAt,omitempty"`
						Url *string `json:"url,omitempty"`
		
	}
		
	
		
	
	// 
	type EnrichRequest struct {
						Config interface{} `json:"config"`
						Context Context `json:"context"`
		
	}
		
	
		
	
	// 
	type EnrichResponse struct {
						Context Context `json:"context"`
		
	}
		
	
		
	
	// 
	type FetchParams struct {
						TargetDate string `json:"targetDate"`
		
	}
		
	
		
	
	// 
	type FetchRequest struct {
						Config interface{} `json:"config"`
						Params FetchParams `json:"params"`
		
	}
		
	
		
	
	// 
	type FetchResponse struct {
						Activities []Activity `json:"activities"`
		
	}
		
	
		
	
	// 
	type MatchContextRequest struct {
						Config interface{} `json:"config"`
						Urls []string `json:"urls"`
		
	}
		
	
		
	
	// 
	type MatchContextResponse struct {
						Results []MatchContextResult `json:"results"`
		
	}
		
	
		
	
	// 
	type MatchContextResult struct {
						Contexts []Context `json:"contexts"`
						Url string `json:"url"`
		
	}
		
	
		
	
	// 
	type TestConnectionRequest struct {
						// Connector configuration including credentials
				Config interface{} `json:"config"`
		
	}
		
	


